### ISSUE TITLE
Error with Seeds

### ISSUE THREAD

**Issue by gregorskii** [99xt/serverless-dynamodb-local#39] opened 2016-07-24 18:31 UTC
The seeds field on a provision file cannot be omitted or else you get this error:

```
Unhandled rejection TypeError: Cannot read property 'map' of undefined
```

You cannot create an empty array or else you get this error:

```
ValidationException: The batch write request list for a table cannot be null or empty: products
```

Suggest code checks for a seeds array before running `dynamodb-migrations` on https://github.com/99xt/serverless-dynamodb-local/blob/master/index.js#L193

**Comment by AshanFernando** [comment] 2016-07-25 05:40
The issue is fixed in the core dependency library dynamodb-migrations (https://github.com/99xt/dynamodb-migrations) and updated the latest version for serverless-dynamodb-local. Latest version (0.2.8) in NPM(https://www.npmjs.com/package/serverless-dynamodb-local) has the update.

**Closed** 2016-07-26 03:29 UTC
Labels: bug
